# Generated by Django 4.1.2 on 2022-10-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Prace'),
        ),
    ]
