# Generated by Django 4.1.2 on 2022-10-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_order_name_products_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
